### ISSUE TITLE
Promise.all not working on Safari 6.1 with an empty array of promise

### ISSUE THREAD

**Issue by astik** [dracupid/light-promise#1]
The problem does not occur on Chrome or newer version of Safari.

Here is the current code for Promise.all :

``` js
    Promise.all = function(promises) {
      var done, finish, fn, i, j, len, p, promise, result;
      promise = new Promise();
      result = new Array(promise.length);
      finish = 0;
      done = false;
      fn = function(i) {
        return p.then(function(rs) {
          result[i] = rs;
          if (++finish === promises.length && !done) {
            return promise.resolve(result);
          }
        }, function(err) {
          done = true;
          return promise.reject(err);
        });
      };
      for (i = j = 0, len = promises.length; j < len; i = ++j) {
        p = promises[i];
        fn(i);
      }
      return promise;
    };
```

If 'promises' input is an empty array, the function will return "new Promise();" with no resolving.

An easy fix would be to add this at function startup :

``` js
if (!promises || promises.length === 0) {
   return Promise.resolve([]);
}
```

**Comment by astik** [comment]
Speaking of this instruction, is this code :

``` js
result = new Array(promise.length);
```

should rather be :

``` js
result = new Array(promises.length);
```

(see the extra s)

**Comment by dracupid** [comment]
Thank you for your correction. I can't figure out why this bug doesn't occurs on Chrome and new safari (I have tried chrome 50 and the bug did exist). According to the code, it won't enter the loop and will always return a Promise with no resolving when input is an empty array.

I wrote this project to have a better understanding about `promise`, it is not quite well-tested and is not supposed to be used in production. If you want a `Promise` polyfill for a normal project, there are many faster and more stable alternatives, like [yaku](https://github.com/ysmood/yaku), [bluebird](https://github.com/petkaantonov/bluebird) and [more](https://github.com/ysmood/yaku#compare-to-other-promise-libs), you can choose according to you requirement.

**Comment by astik** [comment]
In fact, I went for your promise implementation as it is very simple and very lightweight. My need was to work with promise to load a bunch of asset at application startup. Then, my more complex needs are covered by Angular (and $q for the promise part).
So that, your project is perfect for me =)

**Comment by dracupid** [comment]
HTH. Can you show more information about what happened on Safari 6.1?

**Comment by astik** [comment]
On Safari 6.1, Promise.all doesn't resolve at all, so that, callbacks associated to then or catch does not get triggered.

**Comment by astik** [comment]
On Safari 6.1, Promise.all doesn't resolve at all, so that, callbacks associated to then or catch does not get triggered.

**Comment by astik** [comment]
On Safari 6.1, Promise.all doesn't resolve at all, so that, callbacks associated to then or catch does not get triggered.

**Comment by dracupid** [comment]
But this should always occur and I have tested on latest Chrome. ❓

**Comment by dracupid** [comment]
You can also refer to https://github.com/ysmood/yaku/blob/master/docs/minPromiseAplus.js, a minimum promise implementation written by my ex-colleague, who is an expert in this field.

**Comment by astik** [comment]
Agree, this should always occur, on every browser.
Still, we didn't have problem with it until testing on Safari 6.

For our project need, your library is perfect and match what we are looking for, I won't change now =P
